# improvement_agent/loop.py
#
# The Improvement Agent — fixes a script that failed the quality gate.
#
# This is the simplest agent in the system:
# - No tools (like the script agent)
# - No loop (single API call)
# - Targeted input: script + specific eval feedback
# - Same output schema: VideoScript
#
# The key insight: specialised agents outperform general agents.
# Asking the script agent to "try again and do better" produces marginal gains.
# Giving the improvement agent specific failure reasons produces targeted fixes.

import json
import re
from openai import OpenAI
from improvement_agent.prompts import IMPROVEMENT_SYSTEM_PROMPT, build_improvement_prompt
from models.schemas import VideoScript


MODEL = "gpt-4o"
client = OpenAI()


def run_improvement_agent(script: VideoScript, eval_feedback: str) -> VideoScript:
    """
    Improve a script based on specific eval feedback.

    Parameters
    ----------
    script : VideoScript
        The script that failed the quality gate.
    eval_feedback : str
        Human-readable description of what failed and why,
        generated by format_eval_feedback() from the gate scores.

    Returns
    -------
    VideoScript — the improved version
    """
    print(f"\n[Improvement Agent] Starting targeted improvement...")
    print(f"[Improvement Agent] Feedback:\n{eval_feedback}")

    script_json = json.dumps(script.model_dump(), indent=2, ensure_ascii=False)

    messages = [
        {"role": "system", "content": IMPROVEMENT_SYSTEM_PROMPT},
        {"role": "user", "content": build_improvement_prompt(script_json, eval_feedback)},
    ]

    print("[Improvement Agent] Calling model...")

    response = client.chat.completions.create(
        model=MODEL,
        messages=messages,
        max_tokens=4096,
        temperature=0.5,    # Lower temperature than script agent
                            # We want targeted fixes, not creative reinterpretation
    )

    raw = response.choices[0].message.content or ""
    print(f"[Improvement Agent] Received {len(raw):,} characters")

    return _parse_improved_script(raw, script)


def _parse_improved_script(text: str, original: VideoScript) -> VideoScript:
    """
    Parse the improved script. Fall back to original if parsing fails.

    Why fall back instead of raising? Because a failed improvement is better
    than a crashed pipeline. The gate will evaluate the "improved" script —
    if it's still the original, the score won't improve and the gate will
    eventually save with a warning rather than looping forever.
    """
    text = text.strip()

    fence_match = re.search(r'```(?:json)?\s*(\{.*?\})\s*```', text, re.DOTALL)
    if fence_match:
        json_str = fence_match.group(1)
    else:
        first = text.find('{')
        last = text.rfind('}')
        json_str = text[first:last+1] if first != -1 and last != -1 else text

    try:
        data = json.loads(json_str.strip())
        improved = VideoScript(**data)
        print(f"[Improvement Agent] ✓ Improved script parsed")
        print(f"[Improvement Agent]   Title: {improved.seo.title}")
        return improved
    except Exception as e:
        print(f"[Improvement Agent] ✗ Parse failed: {e} — returning original")
        return original


def format_eval_feedback(eval_result: dict) -> str:
    """
    Convert eval scores into human-readable feedback for the improvement agent.

    Takes the output of score_script() from evals/eval_script.py and
    produces a targeted instruction string.
    """
    lines = [f"Overall score: {eval_result['total']}/10\n"]
    lines.append("Issues to fix:")

    breakdown = eval_result.get("breakdown", {})

    for criterion, details in breakdown.items():
        score = details.get("score", 0)
        reason = details.get("reason", "")

        if score < 2:
            severity = "MUST FIX" if score == 0 else "SHOULD FIX"
            lines.append(f"\n{severity} — {criterion} ({score}/2)")
            lines.append(f"  Problem: {reason}")

            # Add specific fix instruction per criterion
            if criterion == "hook_quality":
                lines.append("  Fix: Rewrite the hook section opening. Start with a specific")
                lines.append("  scene, time, or counterintuitive statistic. No 'Imagine...' or")
                lines.append("  'What if I told you...' allowed.")
            elif criterion == "title_specificity":
                lines.append("  Fix: Rewrite seo.title and seo.title_variants.")
                lines.append("  Must include a specific number, timeframe, or direct challenge.")
            elif criterion == "structure_completeness":
                lines.append("  Fix: Add missing section types without removing existing ones.")
                lines.append("  Required: hook, problem or agitation, 2+ main_point sections, cta.")
            elif criterion == "visual_direction":
                lines.append("  Fix: Rewrite visual_direction for each section.")
                lines.append("  Must be specific enough to execute without asking questions.")
            elif criterion == "length_accuracy":
                lines.append("  Fix: Adjust section scripts so word count matches claimed duration.")
                lines.append("  Target: 130-150 words per minute of claimed duration.")

    return "\n".join(lines)
